### ISSUE TITLE
Reuse / License?

### ISSUE THREAD

**Issue by ospringauf** [ShellAddicted/BNO055ESP32#1]
Thanks for your great work. I've been looking at different BNO055 libs and yours seems to work really well and the code is well structured. It would be great if I could use it in my robot vehicle project (https://bitbucket.org/ospringauf/mecanumrover). Unfortunately, I cannot do that, because my project uses the Eclipse Public License (EPL) which is incompatible with your license (GPL). Is there a specific reason why you chose the GPL?

**Comment by ShellAddicted** [comment]
I'm planning to switch to MIT License.
see (380da3256f0fb7298c03dadae358a7ff492444a7) this should help you with your project.
anyway (even if it is not necessary) you have my permission to use this library in your project (https://bitbucket.org/ospringauf/mecanumrover) obviously inside the limits of MIT license.

this library is not finished so let me know if you detect issues.

Thanks for your interest, and have fun with your project!

**Comment by ospringauf** [comment]
That's great, thank you very much (and excuse me for bothering you with such an issue)!
So far, your library seems to work great. I plan to use the BNO055 in NDOF mode as a compensated compass for movement on a flat surface, so I will probably use only very few of its features. But my ESP32 is running multiple tasks, so I'll have to see if everything works well together.
